name: schedview
channels:
 - conda-forge
dependencies:
 - tabulate
 - rubin-scheduler
 - bokeh
 - pytest-flake8
 - pytest-black
 - selenium
 - firefox
 - geckodriver
 - build
 - pip
 - pip:
   - lsst.resources
