"""Summary of schedview.plot.prenighttable

Provides utility functions for display of tables of prenight simulations.
Input data frames are those generated by
``schedview.collect.prenightindex.get_prenight_index_from_database``
or
``schedview.collect.prenightindex.get_prenight_index_from_bucket``.
"""

from collections.abc import Mapping, Sequence
from types import MappingProxyType

import pandas as pd

from schedview import DayObs


def prenight_html_for_telescope(
    day_obs: str | DayObs,
    this_telescope_prenights: pd.DataFrame,
    link_template: str = (
        "https://usdf-rsp.slac.stanford.edu/times-square/github/lsst/schedview_notebooks/prenight/prenight?"
        "day_obs={day_obs}&sim_date={sim_creation_day_obs}&sim_index={daily_id}"
    ),
    columns: Sequence[str] = (
        "sim_creation_day_obs",
        "daily_id",
        "simulation",
        "first_day_obs",
        "last_day_obs",
        "scheduler_version",
        "tags",
    ),
    column_titles: Mapping[str, str] = MappingProxyType(
        {
            "sim_creation_day_obs": "Date simulation was run",
            "daily_id": "id",
        }
    ),
):
    """Generate an HTML table showing the prenight information for a given
    telescope.

    Parameters
    ----------
    day_obs : `str`, `int`, or `DayObs`
        The night for which simulation are to be listed,
        as a SITCOMTN-32 dayobs (YYYYMMDD encoded as an int, YYYY-MM-DD
        as as string, or an instance).
        This value is interpolated into the `link_template` as ``{day_obs}``.
    this_telescope_prenights : `pd.DataFrame`
        DataFrame containing the prenight records for a single telescope.
        It must contain the columns referenced in ``columns`` and in
        ``link_template``.
    link_template : `str`
        URL template used to create a clickable link for each prenight.
        Placeholder values are replaced by the corresponding columns in the
        DataFrame.
        The template is formatted with ``day_obs`` and all key/value pairs from
        ``row.to_dict()``.
    columns : `Sequence` of `str`
        Ordered list of column names to include in the resulting HTML table.
        These columns are extracted from ``this_telescope_prenights`` in the
        order
        given.
    column_titles : `Mapping`
        Mapping of original column names to display titles.
        Only keys present in ``column_titles`` will be renamed; missing keys
        keep their original names.

    Returns
    -------
    table_html : `str`
        An HTML string produced by ``DataFrame.to_html``.
        Each row’s ``simulation`` column contains a link generated from
        ``link_template`` pointing to the detailed prenight page.

    Notes
    -----
    - The function assumes that the ``visitseq_label`` column exists in
      ``this_telescope_prenights`` and is used as the link text.
    - ``link_template`` may contain additional placeholders beyond those
      listed; they will be filled with values from the DataFrame.
    """
    day_obs = DayObs.from_date(day_obs)
    assert isinstance(day_obs, DayObs)

    def make_prenight_link(row):
        url = link_template.format(day_obs=str(day_obs), **row.to_dict())
        return f'<a href={url} target="_blank" rel="noopener noreferrer">{row.visitseq_label}</a>'

    prenight_html = (
        this_telescope_prenights.assign(
            simulation=this_telescope_prenights.apply(make_prenight_link, axis="columns")
        )
        .loc[:, list(columns)]
        .rename(columns=dict(column_titles))
    ).to_html(escape=False)
    return prenight_html
