[project]
title = "schedview"
copyright = "Copyright 2023 Fermi Research Alliance, LLC."
author = "Eric Neilsen"
base_url = "https://schedview.lsst.io"
github_url = "https://github.com/lsst/schedview"

[project.python]
package="schedview"

[sphinx]
extensions = ["sphinx.ext.viewcode"]
